#! /usr/bin/env bash

cat <<END
Content-Type: text/html

<!doctype html>
<html>
  <head>
    <meta charset=utf-8>
    <title>Hello world</title>
  </head>
  <body>
    <h1>Hello world</h1>
    <p>If you're seeing this, it means fastcgi is working.</p>
  </body>
</html>
END
